package com.github.ebina4yaka.volumioplayer.entity

data class VolumioState(
    val status: String = "",
    val position: Long = 0,
    val title: String = "",
    val artist: String = "",
    val album: String = "",
    val albumart: String = "",
    val uri: String = "",
    val trackType: String = "",
    val seek: Long = 0,
    val duration: Long = 0,
    val samplerate: String = "",
    val bitdepth: String = "",
    val channels: Long = 0,
    val random: Boolean = false,
    val repeat: Boolean = false,
    val repeatSingle: Boolean = false,
    val consume: Boolean = false,
    val volume: Long = 0,
    val disableVolumeControl: Boolean = false,
    val mute: Boolean = false,
    val stream: String = "",
    val updatedb: Boolean = false,
    val volatile: Boolean = false,
    val service: String = "",
)